name: horizon_hub
description: "A multiplatform information system for monitoring and controlling project processes, enhancing communication and decision-making efficiency."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.5.0

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  oauth2_client: ^3.2.1
  global_configs: ^1.1.2
  shared_preferences: ^2.2.0
  jwt_decode: ^0.3.1
  flutter_bloc: ^8.1.6
  go_router: ^14.2.0
  intl: any
  get_it: ^7.2.0
  http: ^1.2.2
  equatable: ^2.0.3
  path_provider: ^2.0.2
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  generate: true
